apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cleanup-services
  namespace: default
spec:
  schedule: 0 0 * * * # Runs daily at midnight
  workflowSpec:
    entrypoint: cleanup-services
    templates:
      - name: cleanup-services
        outputs:
          parameters:
            - name: cleanup-services
              valueFrom:
                path: /tmp/result.txt
        script:
          image: bitnami/kubectl:latest
          command:
            - sh
          source: |
            #!/bin/sh
            cd /tmp
            touch result.txt
            echo "Scanning for Services without Endpoints..."
            count=0
            for namespace in $(kubectl get namespaces -o jsonpath='{.items[*].metadata.name}'); do
              for service in $(kubectl get svc -n $namespace -o jsonpath='{.items[*].metadata.name}'); do
                endpoints=$(kubectl get endpoints $service -n $namespace -o jsonpath='{.subsets}' 2>/dev/null)
                if [ -z "$endpoints" ]; then
                  kubectl delete svc $service -n $namespace
                  count=$((count + 1))
                fi
              done
            done
            echo "Deleted $count Services without Endpoints." > /tmp/result.txt
