apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cleanup-crashloopbackoff-pods
  namespace: default
spec:
  schedule: 0 0 * * * # Runs daily at midnight
  workflowSpec:
    entrypoint: cleanup-crashloopbackoff-pods
    templates:
      - name: cleanup-crashloopbackoff-pods
        outputs:
          parameters:
            - name: cleanup-crashloopbackoff-pods
              valueFrom:
                path: /tmp/result.txt
        script:
          image: bitnami/kubectl:latest
          command:
            - sh
          source: |
            #!/bin/sh
            cd /tmp
            touch result.txt
            echo "Cleaning up CrashLoopBackOff pods..."
            count=0
            for namespace in $(kubectl get namespaces -o jsonpath='{.items[*].metadata.name}'); do
              for pod in $(kubectl get pods -n $namespace --field-selector=status.phase=Running -o jsonpath='{.items[?(@.status.containerStatuses[0].state.waiting.reason=="CrashLoopBackOff")].metadata.name}'); do
                kubectl delete pod $pod -n $namespace
                count=$((count + 1))
              done
            done
            echo "Deleted $count CrashLoopBackOff pods." > /tmp/result.txt
